### ISSUE TITLE
readme for w/out multiple gpus

### ISSUE THREAD

**Issue by zehranrgi** [hellozhuo/msgc#2]
Can you also share the readme for one GPU? How to use your models w/out the distributed method?

**Comment by hellozhuo** [comment]
Hi, it can be done by simply changing "CUDA_VISIBLE_DEVICES" and "--nproc_per_node" in the script. In addition, you might also need to reduce the batch size to fit the gpu memory (also reduce the learning rate if the batch size is reduced). For example:
##### ResNet-18 with MSGC w/o attention on 2 gpus
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --master_port=12345 --nproc_per_node=2 main_dist.py --model msgc_resnet18 -j 16 --data imagenet --datadir /to/imagenet/dataset --savedir ./results --resume --target 0.49

##### ResNet-18 with MSGC w/o attention on 1 gpu
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --master_port=12345 --nproc_per_node=1 main_dist.py --model msgc_resnet18 -j 16 --data imagenet --datadir /to/imagenet/dataset --savedir ./results --resume --target 0.49  -b 64 --lr 0.04

**Comment by zehranrgi** [comment]
ok, thank you!
